#pragma once

#ifndef _PINCONSTANTS_H_
#define _PINCONSTANTS_H_

#define ANALOG_RESOLUTION 4096

#define PIN_33_RPM 5
#define PIN_45_RPM 6

#define PIN_SOLENOID_HOLD_OUTPUT 7
#define PIN_SOLENOID_UP_OUTPUT 8

#define PIN_PLAY_LED 9
#define PIN_ROTATE_LED 10
#define PIN_STOP_LED 11

#define PIN_33_LED 12
#define PIN_45_LED 13

#define PIN_RED_DISK_LED 14
#define PIN_GREEN_DISK_LED 15
#define PIN_BLUE_DISK_LED 16

#define PIN_PICKUP_RELAY 17
#define PIN_DAMPER_RELAY 18

#define PIN_TONEARM_VOLTAGE_OUTPUT DAC0

#define PIN_ANTISCATE A0
#define PIN_DAMPER A1
#define PIN_JOYSTICK_UP_DOWN A2
#define PIN_JOYSTICK_LEFT_RIGHT A3

#endif